#############################################################################
# Makefile for building: com_evasyst_qtstomp.app/Contents/MacOS/com_evasyst_qtstomp
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  com/evasyst/com_evasyst_qtstomp.pro
# Template: app
# Command: /Users/jordanbaucke/Qt/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile com/evasyst/com_evasyst_qtstomp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -Icom/evasyst -I. -I../../../Qt/5.6/clang_64/lib/QtQuick.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtWebSockets.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.6/clang_64/mkspecs/macx-clang -F/Users/jordanbaucke/Qt/5.6/clang_64/lib
QMAKE         = /Users/jordanbaucke/Qt/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = com_evasyst_qtstomp4.5
DISTDIR = /Users/jordanbaucke/Documents/workspace/qtstomp/.tmp/com_evasyst_qtstomp4.5
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/jordanbaucke/Qt/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jordanbaucke/Qt/5.6/clang_64/lib -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework QtWebSockets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = com/evasyst/qstompconnectframe.cpp \
		com/evasyst/qstompconnection.cpp \
		com/evasyst/qstompframe.cpp \
		com/evasyst/qstompframebody.cpp \
		com/evasyst/qstompframebodytext.cpp \
		com/evasyst/qtstomp.cpp \
		com/evasyst/qtstompwrapper.cpp qrc_com_evasyst_qtstomp.cpp \
		moc_qstompconnection.cpp \
		moc_qtstompwrapper.cpp
OBJECTS       = qstompconnectframe.o \
		qstompconnection.o \
		qstompframe.o \
		qstompframebody.o \
		qstompframebodytext.o \
		qtstomp.o \
		qtstompwrapper.o \
		qrc_com_evasyst_qtstomp.o \
		moc_qstompconnection.o \
		moc_qtstompwrapper.o
DIST          = com/evasyst/qmldir \
		../Qt/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.6/clang_64/mkspecs/qdevice.pri \
		../Qt/5.6/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.6/clang_64/mkspecs/common/unix.conf \
		../Qt/5.6/clang_64/mkspecs/common/mac.conf \
		../Qt/5.6/clang_64/mkspecs/common/macx.conf \
		../Qt/5.6/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.6/clang_64/mkspecs/common/clang.conf \
		../Qt/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.6/clang_64/mkspecs/qconfig.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.6/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.6/clang_64/mkspecs/features/spec_post.prf \
		../Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.6/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		com/evasyst/com/evasyst/com_evasyst_qtstomp.pri \
		../Qt/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.6/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.6/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.6/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.6/clang_64/mkspecs/features/qt.prf \
		../Qt/5.6/clang_64/mkspecs/features/resources.prf \
		../Qt/5.6/clang_64/mkspecs/features/moc.prf \
		../Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.6/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.6/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.6/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.6/clang_64/mkspecs/features/lex.prf \
		com/evasyst/com/evasyst/com_evasyst_qtstomp.pro com/evasyst/qstompconnectframe.h \
		com/evasyst/qstompconnection.h \
		com/evasyst/qstompframe_p.h \
		com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qstompframebodytext.h \
		com/evasyst/qtstomp.h \
		com/evasyst/qtstompwrapper.h com/evasyst/qstompconnectframe.cpp \
		com/evasyst/qstompconnection.cpp \
		com/evasyst/qstompframe.cpp \
		com/evasyst/qstompframebody.cpp \
		com/evasyst/qstompframebodytext.cpp \
		com/evasyst/qtstomp.cpp \
		com/evasyst/qtstompwrapper.cpp
QMAKE_TARGET  = com_evasyst_qtstomp
DESTDIR       = 
TARGET        = com_evasyst_qtstomp.app/Contents/MacOS/com_evasyst_qtstomp


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d com_evasyst_qtstomp.app/Contents/MacOS/ || mkdir -p com_evasyst_qtstomp.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: com/evasyst/com_evasyst_qtstomp.pro ../../../Qt/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.6/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		com/evasyst/com_evasyst_qtstomp.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/lex.prf \
		com/evasyst/com_evasyst_qtstomp.pro \
		com/evasyst/com_evasyst_qtstomp.qrc \
		../../../Qt/5.6/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/QtQml.prl \
		../../../Qt/5.6/clang_64/lib/QtWebSockets.framework/QtWebSockets.prl \
		../../../Qt/5.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile com/evasyst/com_evasyst_qtstomp.pro
../../../Qt/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.6/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.6/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.6/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.6/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.6/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.6/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.6/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.6/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.6/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.6/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.6/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
com/evasyst/com_evasyst_qtstomp.pri:
../../../Qt/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.6/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.6/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.6/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.6/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.6/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.6/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.6/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.6/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.6/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.6/clang_64/mkspecs/features/lex.prf:
com/evasyst/com_evasyst_qtstomp.pro:
com/evasyst/com_evasyst_qtstomp.qrc:
../../../Qt/5.6/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../../Qt/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.6/clang_64/lib/QtQml.framework/QtQml.prl:
../../../Qt/5.6/clang_64/lib/QtWebSockets.framework/QtWebSockets.prl:
../../../Qt/5.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile com/evasyst/com_evasyst_qtstomp.pro

qmake_all: FORCE

com_evasyst_qtstomp.app/Contents/PkgInfo: 
	@test -d com_evasyst_qtstomp.app/Contents || mkdir -p com_evasyst_qtstomp.app/Contents
	@$(DEL_FILE) com_evasyst_qtstomp.app/Contents/PkgInfo
	@echo "APPL????" > com_evasyst_qtstomp.app/Contents/PkgInfo
com_evasyst_qtstomp.app/Contents/Resources/empty.lproj: 
	@test -d com_evasyst_qtstomp.app/Contents/Resources || mkdir -p com_evasyst_qtstomp.app/Contents/Resources
	@touch com_evasyst_qtstomp.app/Contents/Resources/empty.lproj
	
com_evasyst_qtstomp.app/Contents/Info.plist: 
	@test -d com_evasyst_qtstomp.app/Contents || mkdir -p com_evasyst_qtstomp.app/Contents
	@$(DEL_FILE) com_evasyst_qtstomp.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,4.5,g" -e "s,@FULL_VERSION@,4.5.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.obs-studio.com-evasyst-qtstomp,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,com_evasyst_qtstomp,g" -e "s,@LIBRARY@,com_evasyst_qtstomp,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >com_evasyst_qtstomp.app/Contents/Info.plist

all: Makefile \
		com_evasyst_qtstomp.app/Contents/PkgInfo \
		com_evasyst_qtstomp.app/Contents/Resources/empty.lproj \
		com_evasyst_qtstomp.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents com/evasyst/com_evasyst_qtstomp.qrc $(DISTDIR)/
	$(COPY_FILE) --parents com/evasyst/qstompconnectframe.h com/evasyst/qstompconnection.h com/evasyst/qstompframe_p.h com/evasyst/qstompframe.h com/evasyst/qstompframebody.h com/evasyst/qstompframebodytext.h com/evasyst/qtstomp.h com/evasyst/qtstompwrapper.h $(DISTDIR)/
	$(COPY_FILE) --parents com/evasyst/qstompconnectframe.cpp com/evasyst/qstompconnection.cpp com/evasyst/qstompframe.cpp com/evasyst/qstompframebody.cpp com/evasyst/qstompframebodytext.cpp com/evasyst/qtstomp.cpp com/evasyst/qtstompwrapper.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r com_evasyst_qtstomp.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_com_evasyst_qtstomp.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_com_evasyst_qtstomp.cpp
qrc_com_evasyst_qtstomp.cpp: com/evasyst/com_evasyst_qtstomp.qrc \
		com/evasyst/qmldir \
		com/evasyst/network.js \
		com/evasyst/main.qml
	/Users/jordanbaucke/Qt/5.6/clang_64/bin/rcc -name com_evasyst_qtstomp com/evasyst/com_evasyst_qtstomp.qrc -o qrc_com_evasyst_qtstomp.cpp

compiler_moc_header_make_all: moc_qstompconnection.cpp moc_qtstompwrapper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qstompconnection.cpp moc_qtstompwrapper.cpp
moc_qstompconnection.cpp: com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		com/evasyst/qtstompwrapper.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompconnection.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qstompframebodytext.h \
		com/evasyst/qstompconnection.h
	/Users/jordanbaucke/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/jordanbaucke/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/jordanbaucke/Documents/workspace/qtstomp/com/evasyst -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtQuick.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtQml.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtWebSockets.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtCore.framework/Headers -I. -F/Users/jordanbaucke/Qt/5.6/clang_64/lib com/evasyst/qstompconnection.h -o moc_qstompconnection.cpp

moc_qtstompwrapper.cpp: ../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompconnection.h \
		com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		com/evasyst/qtstompwrapper.h \
		com/evasyst/qstompframebodytext.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qtstompwrapper.h
	/Users/jordanbaucke/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/jordanbaucke/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/jordanbaucke/Documents/workspace/qtstomp/com/evasyst -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtQuick.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtQml.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtWebSockets.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/jordanbaucke/Qt/5.6/clang_64/lib/QtCore.framework/Headers -I. -F/Users/jordanbaucke/Qt/5.6/clang_64/lib com/evasyst/qtstompwrapper.h -o moc_qtstompwrapper.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

qstompconnectframe.o: com/evasyst/qstompconnectframe.cpp com/evasyst/qstompconnectframe.h \
		com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		com/evasyst/qtstompwrapper.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompconnection.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qstompframebodytext.h \
		com/evasyst/qstompframe_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qstompconnectframe.o com/evasyst/qstompconnectframe.cpp

qstompconnection.o: com/evasyst/qstompconnection.cpp com/evasyst/qstompconnection.h \
		com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		com/evasyst/qtstompwrapper.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompframebodytext.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qstompconnectframe.h \
		../../../Qt/5.6/clang_64/lib/QtWebSockets.framework/Headers/QWebSocket \
		../../../Qt/5.6/clang_64/lib/QtWebSockets.framework/Headers/qwebsocket.h \
		../../../Qt/5.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt/5.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qstompconnection.o com/evasyst/qstompconnection.cpp

qstompframe.o: com/evasyst/qstompframe.cpp com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		com/evasyst/qtstompwrapper.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompconnection.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qstompframebodytext.h \
		com/evasyst/qstompframe_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qstompframe.o com/evasyst/qstompframe.cpp

qstompframebody.o: com/evasyst/qstompframebody.cpp com/evasyst/qstompframebody.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qstompframebody.o com/evasyst/qstompframebody.cpp

qstompframebodytext.o: com/evasyst/qstompframebodytext.cpp com/evasyst/qstompframebodytext.h \
		com/evasyst/qstompframebody.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qstompframebodytext.o com/evasyst/qstompframebodytext.cpp

qtstomp.o: com/evasyst/qtstomp.cpp com/evasyst/qtstompwrapper.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompconnection.h \
		com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qstompframebodytext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtstomp.o com/evasyst/qtstomp.cpp

qtstompwrapper.o: com/evasyst/qtstompwrapper.cpp com/evasyst/qtstompwrapper.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/QtQml \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../../../Qt/5.6/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qhash.h \
		com/evasyst/qstompconnection.h \
		com/evasyst/qstompframe.h \
		com/evasyst/qstompframebody.h \
		com/evasyst/qtstomp.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		com/evasyst/qstompframebodytext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtstompwrapper.o com/evasyst/qtstompwrapper.cpp

qrc_com_evasyst_qtstomp.o: qrc_com_evasyst_qtstomp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_com_evasyst_qtstomp.o qrc_com_evasyst_qtstomp.cpp

moc_qstompconnection.o: moc_qstompconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qstompconnection.o moc_qstompconnection.cpp

moc_qtstompwrapper.o: moc_qtstompwrapper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtstompwrapper.o moc_qtstompwrapper.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

